// This file is generated by omniidl (C++ backend)- omniORB_4_3. Do not edit.
#ifndef __SimpleIDL_hh__
#define __SimpleIDL_hh__

#ifndef __CORBA_H_EXTERNAL_GUARD__
#include <omniORB4/CORBA.h>
#endif

#ifndef  USE_stub_in_nt_dll
# define USE_stub_in_nt_dll_NOT_DEFINED_SimpleIDL
#endif
#ifndef  USE_core_stub_in_nt_dll
# define USE_core_stub_in_nt_dll_NOT_DEFINED_SimpleIDL
#endif
#ifndef  USE_dyn_stub_in_nt_dll
# define USE_dyn_stub_in_nt_dll_NOT_DEFINED_SimpleIDL
#endif






#ifdef USE_stub_in_nt_dll
# ifndef USE_core_stub_in_nt_dll
#  define USE_core_stub_in_nt_dll
# endif
# ifndef USE_dyn_stub_in_nt_dll
#  define USE_dyn_stub_in_nt_dll
# endif
#endif

#ifdef _core_attr
# error "A local CPP macro _core_attr has already been defined."
#else
# ifdef  USE_core_stub_in_nt_dll
#  define _core_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _core_attr
# endif
#endif

#ifdef _dyn_attr
# error "A local CPP macro _dyn_attr has already been defined."
#else
# ifdef  USE_dyn_stub_in_nt_dll
#  define _dyn_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _dyn_attr
# endif
#endif



class LongArray_var;

class LongArray : public _CORBA_Unbounded_Sequence_w_FixSizeElement< ::CORBA::Long, 4, 4 >  {
public:
  typedef LongArray_var _var_type;
  inline LongArray() {}
  inline LongArray(const LongArray& _s)
    : _CORBA_Unbounded_Sequence_w_FixSizeElement< ::CORBA::Long, 4, 4 > (_s) {}

  inline LongArray(_CORBA_ULong _max)
    : _CORBA_Unbounded_Sequence_w_FixSizeElement< ::CORBA::Long, 4, 4 > (_max) {}
  inline LongArray(_CORBA_ULong _max, _CORBA_ULong _len, ::CORBA::Long* _val, _CORBA_Boolean _rel=0)
    : _CORBA_Unbounded_Sequence_w_FixSizeElement< ::CORBA::Long, 4, 4 > (_max, _len, _val, _rel) {}



  inline LongArray& operator = (const LongArray& _s) {
    _CORBA_Unbounded_Sequence_w_FixSizeElement< ::CORBA::Long, 4, 4 > ::operator=(_s);
    return *this;
  }
};

class LongArray_out;

class LongArray_var {
public:
  inline LongArray_var() : _pd_seq(0) {}
  inline LongArray_var(LongArray* _s) : _pd_seq(_s) {}
  inline LongArray_var(const LongArray_var& _s) {
    if (_s._pd_seq)  _pd_seq = new LongArray(*_s._pd_seq);
    else             _pd_seq = 0;
  }
  inline ~LongArray_var() { if (_pd_seq)  delete _pd_seq; }
    
  inline LongArray_var& operator = (LongArray* _s) {
    if (_pd_seq)  delete _pd_seq;
    _pd_seq = _s;
    return *this;
  }
  inline LongArray_var& operator = (const LongArray_var& _s) {
    if (&_s != this) {
      if (_s._pd_seq) {
        if (!_pd_seq)  _pd_seq = new LongArray;
        *_pd_seq = *_s._pd_seq;
      }
      else if (_pd_seq) {
        delete _pd_seq;
        _pd_seq = 0;
      }
    }
    return *this;
  }
  inline ::CORBA::Long& operator [] (_CORBA_ULong _s) {
    return (*_pd_seq)[_s];
  }



  inline LongArray* operator -> () { return _pd_seq; }
  inline const LongArray* operator -> () const { return _pd_seq; }
#if defined(__GNUG__)
  inline operator LongArray& () const { return *_pd_seq; }
#else
  inline operator const LongArray& () const { return *_pd_seq; }
  inline operator LongArray& () { return *_pd_seq; }
#endif
    
  inline const LongArray& in() const { return *_pd_seq; }
  inline LongArray&       inout()    { return *_pd_seq; }
  inline LongArray*&      out() {
    if (_pd_seq) { delete _pd_seq; _pd_seq = 0; }
    return _pd_seq;
  }
  inline LongArray* _retn() { LongArray* tmp = _pd_seq; _pd_seq = 0; return tmp; }
    
  friend class LongArray_out;
  
private:
  LongArray* _pd_seq;
};

class LongArray_out {
public:
  inline LongArray_out(LongArray*& _s) : _data(_s) { _data = 0; }
  inline LongArray_out(LongArray_var& _s)
    : _data(_s._pd_seq) { _s = (LongArray*) 0; }
  inline LongArray_out(const LongArray_out& _s) : _data(_s._data) {}
  inline LongArray_out& operator = (const LongArray_out& _s) {
    _data = _s._data;
    return *this;
  }
  inline LongArray_out& operator = (LongArray* _s) {
    _data = _s;
    return *this;
  }
  inline operator LongArray*&()  { return _data; }
  inline LongArray*& ptr()       { return _data; }
  inline LongArray* operator->() { return _data; }

  inline ::CORBA::Long& operator [] (_CORBA_ULong _i) {
    return (*_data)[_i];
  }



  LongArray*& _data;

private:
  LongArray_out();
  LongArray_out& operator=(const LongArray_var&);
};

#ifndef __MyInterface__
#define __MyInterface__
class MyInterface;
class _objref_MyInterface;
class _impl_MyInterface;

typedef _objref_MyInterface* MyInterface_ptr;
typedef MyInterface_ptr MyInterfaceRef;

class MyInterface_Helper {
public:
  typedef MyInterface_ptr _ptr_type;

  static _ptr_type _nil();
  static _CORBA_Boolean is_nil(_ptr_type);
  static void release(_ptr_type);
  static void duplicate(_ptr_type);
  static void marshalObjRef(_ptr_type, cdrStream&);
  static _ptr_type unmarshalObjRef(cdrStream&);
};

typedef _CORBA_ObjRef_Var<_objref_MyInterface, MyInterface_Helper> MyInterface_var;
typedef _CORBA_ObjRef_OUT_arg<_objref_MyInterface,MyInterface_Helper > MyInterface_out;

#endif

// interface MyInterface
class MyInterface {
public:
  // Declarations for this interface type.
  typedef MyInterface_ptr _ptr_type;
  typedef MyInterface_var _var_type;

  static _ptr_type _duplicate(_ptr_type);
  static _ptr_type _narrow(::CORBA::Object_ptr);
  static _ptr_type _unchecked_narrow(::CORBA::Object_ptr);
  
  static _ptr_type _nil();

  static inline void _marshalObjRef(_ptr_type, cdrStream&);

  static inline _ptr_type _unmarshalObjRef(cdrStream& s) {
    omniObjRef* o = omniObjRef::_unMarshal(_PD_repoId,s);
    if (o)
      return (_ptr_type) o->_ptrToObjRef(_PD_repoId);
    else
      return _nil();
  }

  static inline _ptr_type _fromObjRef(omniObjRef* o) {
    if (o)
      return (_ptr_type) o->_ptrToObjRef(_PD_repoId);
    else
      return _nil();
  }

  static _core_attr const char* _PD_repoId;

  // Other IDL defined within this scope.
  
};

class _objref_MyInterface :
  public virtual ::CORBA::Object,
  public virtual omniObjRef
{
public:
  // IDL operations
  ::CORBA::Long Summa(const ::LongArray& numbers);

  // Constructors
  inline _objref_MyInterface()  { _PR_setobj(0); }  // nil
  _objref_MyInterface(omniIOR*, omniIdentity*);

protected:
  virtual ~_objref_MyInterface();

  
private:
  virtual void* _ptrToObjRef(const char*);

  _objref_MyInterface(const _objref_MyInterface&);
  _objref_MyInterface& operator = (const _objref_MyInterface&);
  // not implemented

  friend class MyInterface;
};

class _pof_MyInterface : public _OMNI_NS(proxyObjectFactory) {
public:
  inline _pof_MyInterface() : _OMNI_NS(proxyObjectFactory)(MyInterface::_PD_repoId) {}
  virtual ~_pof_MyInterface();

  virtual omniObjRef* newObjRef(omniIOR*,omniIdentity*);
  virtual _CORBA_Boolean is_a(const char*) const;
};

class _impl_MyInterface :
  public virtual omniServant
{
public:
  virtual ~_impl_MyInterface();

  virtual ::CORBA::Long Summa(const ::LongArray& numbers) = 0;
  
public:  // Really protected, workaround for xlC
  virtual _CORBA_Boolean _dispatch(omniCallHandle&);

private:
  virtual void* _ptrToInterface(const char*);
  virtual const char* _mostDerivedRepoId();
  
};




class POA_MyInterface :
  public virtual _impl_MyInterface,
  public virtual ::PortableServer::ServantBase
{
public:
  virtual ~POA_MyInterface();

  inline ::MyInterface_ptr _this() {
    return (::MyInterface_ptr) _do_this(::MyInterface::_PD_repoId);
  }
};







#undef _core_attr
#undef _dyn_attr



inline void
MyInterface::_marshalObjRef(::MyInterface_ptr obj, cdrStream& s) {
  omniObjRef::_marshal(obj->_PR_getobj(),s);
}



#ifdef   USE_stub_in_nt_dll_NOT_DEFINED_SimpleIDL
# undef  USE_stub_in_nt_dll
# undef  USE_stub_in_nt_dll_NOT_DEFINED_SimpleIDL
#endif
#ifdef   USE_core_stub_in_nt_dll_NOT_DEFINED_SimpleIDL
# undef  USE_core_stub_in_nt_dll
# undef  USE_core_stub_in_nt_dll_NOT_DEFINED_SimpleIDL
#endif
#ifdef   USE_dyn_stub_in_nt_dll_NOT_DEFINED_SimpleIDL
# undef  USE_dyn_stub_in_nt_dll
# undef  USE_dyn_stub_in_nt_dll_NOT_DEFINED_SimpleIDL
#endif

#endif  // __SimpleIDL_hh__

